apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hw-tst
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: hw
  sources:
    - repoURL: https://helm.github.io/examples
      chart: hello-world
      targetRevision: 0.1.0
      helm:
        valueFiles:
          - $values/values-tst.yaml

    - repoURL: https://github.com/zachath/argo-test
      targetRevision: HEAD
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
